import 'dart:math';

import 'learning_models.dart';

enum CompanionNameCategory {
  workplace,
  campus,
  lowBattery,
  gentleTwist,
  foodSupply,
  absurdEasterEgg,
}

class CompanionNameEntry {
  const CompanionNameEntry({
    required this.id,
    required this.concept,
    required this.zhHant,
    required this.zhHans,
    required this.ja,
    required this.category,
    required this.tone,
    required this.isInitialDefault,
  });

  final int id;
  final String concept;
  final String zhHant;
  final String zhHans;
  final String ja;
  final CompanionNameCategory category;
  final String tone;
  final bool isInitialDefault;

  String nameForLanguage(String languageCode) {
    final normalized = normalizeNativeLanguage(languageCode);
    switch (normalized) {
      case 'zh-Hant':
        return zhHant;
      case 'zh-Hans':
        return zhHans;
      case 'ja':
        return ja;
      default:
        return zhHant;
    }
  }
}

class CompanionNamePool {
  const CompanionNamePool._();

  static const List<CompanionNameEntry> all = [
    CompanionNameEntry(
      id: 1,
      concept: '加班也会发芽',
      zhHant: '加班芽',
      zhHans: '加班芽',
      ja: 'ざんぎょう芽',
      category: CompanionNameCategory.workplace,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 2,
      concept: '会议里只剩点头',
      zhHant: '會議豆',
      zhHans: '会议豆',
      ja: 'かいぎ豆',
      category: CompanionNameCategory.workplace,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 3,
      concept: '通勤像一颗滚动的球',
      zhHant: '通勤球',
      zhHans: '通勤球',
      ja: 'つうきん丸',
      category: CompanionNameCategory.workplace,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 4,
      concept: '周一尚未启动',
      zhHant: '週一待機',
      zhHans: '周一待机',
      ja: '月曜待機',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 5,
      concept: '准时下班是一种信仰',
      zhHant: '下班信徒',
      zhHans: '下班信徒',
      ja: '定時信者',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 6,
      concept: '在办公桌前植物化',
      zhHant: '辦公桌盆栽',
      zhHans: '工位盆栽',
      ja: 'デスク盆栽',
      category: CompanionNameCategory.workplace,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 7,
      concept: '已读后假装很忙',
      zhHant: '已讀裝忙',
      zhHans: '已读装忙',
      ja: '既読多忙',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 8,
      concept: '摸鱼也像正式岗位',
      zhHant: '摸魚專員',
      zhHans: '摸鱼专员',
      ja: '息抜き係',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 9,
      concept: '日报交给明天',
      zhHant: '日報明天寫',
      zhHans: '日报明天写',
      ja: '日報は明日',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 10,
      concept: '静音状态上班',
      zhHant: '靜音上班',
      zhHans: '静音上班',
      ja: 'ミュート勤務',
      category: CompanionNameCategory.workplace,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 11,
      concept: 'KPI 交给缘分',
      zhHant: 'KPI隨緣',
      zhHans: 'KPI随缘',
      ja: 'KPIは運まかせ',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 12,
      concept: '截止前突然认真',
      zhHant: '臨時認真',
      zhHans: '临时认真',
      ja: '急に本気',
      category: CompanionNameCategory.workplace,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 13,
      concept: '在邮件里潜水',
      zhHant: '信箱潛水',
      zhHans: '邮箱潜水',
      ja: 'メール潜水',
      category: CompanionNameCategory.workplace,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 14,
      concept: '准时下班像稀有生物',
      zhHant: '準時下班獸',
      zhHans: '准时下班兽',
      ja: '定時退社獣',
      category: CompanionNameCategory.workplace,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 15,
      concept: '会议核心技能是点头',
      zhHant: '點頭專家',
      zhHans: '点头专家',
      ja: 'うなずき名人',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 16,
      concept: '坐到座位才开始充电',
      zhHant: '座位充電中',
      zhHans: '工位充电中',
      ja: '席で充電中',
      category: CompanionNameCategory.workplace,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 17,
      concept: '待办事项自行繁殖',
      zhHant: '待辦養殖戶',
      zhHans: '待办养殖户',
      ja: 'タスク牧場',
      category: CompanionNameCategory.workplace,
      tone: '荒诞',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 18,
      concept: '最终版永远有下一版',
      zhHant: '最終版之二',
      zhHans: '最终版之二',
      ja: '最終版その二',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 19,
      concept: '努力召唤周五',
      zhHant: '週五召喚師',
      zhHans: '周五召唤师',
      ja: '金曜召喚士',
      category: CompanionNameCategory.workplace,
      tone: '荒诞',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 20,
      concept: '从上班开始倒数下班',
      zhHant: '下班倒數',
      zhHans: '下班倒数',
      ja: '退勤カウント',
      category: CompanionNameCategory.workplace,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 21,
      concept: '第一堂课还没醒',
      zhHant: '早課豆',
      zhHans: '早八豆',
      ja: '一限豆',
      category: CompanionNameCategory.campus,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 22,
      concept: '截止日也会发芽',
      zhHant: '期限芽',
      zhHans: '截止芽',
      ja: 'しめきり芽',
      category: CompanionNameCategory.campus,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 23,
      concept: '作业堆成山',
      zhHant: '作業山',
      zhHans: '作业山',
      ja: '課題マウンテン',
      category: CompanionNameCategory.campus,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 24,
      concept: '点名时暂时隐身',
      zhHant: '點名隱身',
      zhHans: '点名隐身',
      ja: '点呼ステルス',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 25,
      concept: '考前临时祈愿',
      zhHant: '考前祈願',
      zhHans: '考前祈愿',
      ja: 'テスト祈願',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 26,
      concept: '论文交给明天',
      zhHant: '論文明天寫',
      zhHans: '论文明天写',
      ja: '論文は明日',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 27,
      concept: '小组消息先潜水',
      zhHant: '小組潛水員',
      zhHans: '小组潜水员',
      ja: 'グループ潜水',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 28,
      concept: '自习主要在发呆',
      zhHant: '自習發呆王',
      zhHans: '自习发呆王',
      ja: '自習ぼんやり王',
      category: CompanionNameCategory.campus,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 29,
      concept: '追捕逃跑的学分',
      zhHant: '學分捕手',
      zhHans: '学分捕手',
      ja: '単位ハンター',
      category: CompanionNameCategory.campus,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 30,
      concept: '选课全靠手速',
      zhHant: '選課手速王',
      zhHans: '选课手速王',
      ja: '履修クリック王',
      category: CompanionNameCategory.campus,
      tone: '趣味',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 31,
      concept: '报告时大脑卡住',
      zhHant: '報告卡住',
      zhHans: '汇报卡顿',
      ja: '発表フリーズ',
      category: CompanionNameCategory.campus,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 32,
      concept: '口试或答辩靠微笑',
      zhHant: '口試微笑派',
      zhHans: '答辩微笑派',
      ja: '発表スマイル',
      category: CompanionNameCategory.campus,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 33,
      concept: '复习尚未启动',
      zhHant: '複習待啟動',
      zhHans: '复习待启动',
      ja: '復習起動待ち',
      category: CompanionNameCategory.campus,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 34,
      concept: '考试依靠一点直觉',
      zhHant: '考試靠直覺',
      zhHans: '考试靠直觉',
      ja: 'テストは勘',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 35,
      concept: '拍了笔记等于学过',
      zhHant: '筆記攝影師',
      zhHans: '笔记摄影师',
      ja: 'ノート撮影係',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 36,
      concept: '图书馆长期住客',
      zhHant: '圖書館住客',
      zhHans: '图书馆住客',
      ja: '図書館住民',
      category: CompanionNameCategory.campus,
      tone: '共鸣',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 37,
      concept: '永远追着截止时间',
      zhHant: '期限追逐者',
      zhHans: 'DDL追逐者',
      ja: '締切チェイサー',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 38,
      concept: '拖延也能当优等生',
      zhHant: '拖延優等生',
      zhHans: '拖延优等生',
      ja: '後回し優等生',
      category: CompanionNameCategory.campus,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 39,
      concept: '学习从明天开始',
      zhHant: '明天開始讀',
      zhHans: '明天开始读',
      ja: '明日から勉強',
      category: CompanionNameCategory.campus,
      tone: '小腹黑',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 40,
      concept: '毕业进度仍在加载',
      zhHant: '畢業載入中',
      zhHans: '毕业加载中',
      ja: '卒業ロード中',
      category: CompanionNameCategory.campus,
      tone: '小反转',
      isInitialDefault: false,
    ),
    CompanionNameEntry(
      id: 41,
      concept: '总是有点困',
      zhHant: '睏睏',
      zhHans: '困困',
      ja: 'ねむねむ',
      category: CompanionNameCategory.lowBattery,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 42,
      concept: '电量长期不足',
      zhHant: '低電量豆',
      zhHans: '低电量豆',
      ja: 'でんち豆',
      category: CompanionNameCategory.lowBattery,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 43,
      concept: '认真放空',
      zhHant: '放空球',
      zhHans: '放空球',
      ja: 'ぼんやり丸',
      category: CompanionNameCategory.lowBattery,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 44,
      concept: '把事情往后放',
      zhHant: '拖延豆',
      zhHans: '拖延豆',
      ja: 'あとまわし',
      category: CompanionNameCategory.lowBattery,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 45,
      concept: '人生正在缓冲',
      zhHant: '緩衝中',
      zhHans: '缓冲中',
      ja: '読み込み中',
      category: CompanionNameCategory.lowBattery,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 46,
      concept: '稍后恢复灵魂',
      zhHant: '稍後回神',
      zhHans: '稍后回神',
      ja: 'あとで復帰',
      category: CompanionNameCategory.lowBattery,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 47,
      concept: '今天启动失败',
      zhHant: '起床失敗',
      zhHans: '起床失败',
      ja: '起動失敗',
      category: CompanionNameCategory.lowBattery,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 48,
      concept: '周末才恢复生长',
      zhHant: '週末苗',
      zhHans: '周末苗',
      ja: 'しゅうまつ丸',
      category: CompanionNameCategory.lowBattery,
      tone: '共鸣',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 49,
      concept: '身体在线，灵魂离线',
      zhHant: '靈魂離線',
      zhHans: '灵魂离线',
      ja: 'たましいオフ',
      category: CompanionNameCategory.lowBattery,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 50,
      concept: '热情保质期三分钟',
      zhHant: '三分鐘熱度',
      zhHans: '三分钟热度',
      ja: '三日坊主',
      category: CompanionNameCategory.lowBattery,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 51,
      concept: '专门打败闹钟',
      zhHant: '鬧鐘剋星',
      zhHans: '闹钟克星',
      ja: 'アラーム封じ',
      category: CompanionNameCategory.lowBattery,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 52,
      concept: '被沙发吸住',
      zhHant: '沙發磁鐵',
      zhHans: '沙发磁铁',
      ja: 'ソファ磁石',
      category: CompanionNameCategory.lowBattery,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 53,
      concept: '不是不回，只是慢回',
      zhHant: '訊息晚回',
      zhHans: '消息晚回',
      ja: '返信ゆっくり',
      category: CompanionNameCategory.lowBattery,
      tone: '共鸣',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 54,
      concept: '脑内一直转圈',
      zhHant: '腦袋轉圈',
      zhHans: '脑袋转圈',
      ja: '脳内ロード中',
      category: CompanionNameCategory.lowBattery,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 55,
      concept: '反应总慢一点',
      zhHant: '慢半拍',
      zhHans: '慢半拍',
      ja: 'ワンテンポ遅め',
      category: CompanionNameCategory.lowBattery,
      tone: '共鸣',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 56,
      concept: '今天进入省电模式',
      zhHant: '今天省電',
      zhHans: '今天省电',
      ja: '本日省エネ',
      category: CompanionNameCategory.lowBattery,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 57,
      concept: '偶尔才上线',
      zhHant: '偶爾上線',
      zhHans: '偶尔上线',
      ja: 'たまにログイン',
      category: CompanionNameCategory.lowBattery,
      tone: '共鸣',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 58,
      concept: '睡意长期居住',
      zhHant: '睡意常駐',
      zhHans: '睡意常驻',
      ja: '眠気常駐',
      category: CompanionNameCategory.lowBattery,
      tone: '共鸣',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 59,
      concept: '计划也需要休眠',
      zhHant: '計畫休眠',
      zhHans: '计划休眠',
      ja: '計画休眠',
      category: CompanionNameCategory.lowBattery,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 60,
      concept: '元气余额为零',
      zhHant: '元氣餘額零',
      zhHans: '元气余额零',
      ja: '元気残高ゼロ',
      category: CompanionNameCategory.lowBattery,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 61,
      concept: '慢热也可以夺冠',
      zhHant: '慢熱冠軍',
      zhHans: '慢热冠军',
      ja: '遅咲き王',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 62,
      concept: '轻松地拼一把',
      zhHant: '佛系衝刺',
      zhHans: '佛系冲刺',
      ja: 'ゆる全力',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 63,
      concept: '配送一点微光',
      zhHant: '微光派送',
      zhHans: '微光派送',
      ja: 'ひかり便',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 64,
      concept: '今天没输也算赢',
      zhHant: '今天也算贏',
      zhHans: '今天也算赢',
      ja: '今日も勝ち',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 65,
      concept: '把休息练成优点',
      zhHant: '休息優等生',
      zhHans: '休息优等生',
      ja: '休み上手',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 66,
      concept: '不着急也会赢',
      zhHant: '不急著贏',
      zhHans: '不急着赢',
      ja: '急がず勝つ',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 67,
      concept: '小步也可以是冠军',
      zhHant: '小步冠軍',
      zhHans: '小步冠军',
      ja: 'ちいさな一歩王',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 68,
      concept: '发呆也有道理',
      zhHant: '發呆有理',
      zhHans: '发呆有理',
      ja: 'ぼんやり正解',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 69,
      concept: '温柔也能反击',
      zhHant: '溫柔反擊',
      zhHans: '温柔反击',
      ja: 'やさしい反撃',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 70,
      concept: '安静地厉害',
      zhHant: '安靜厲害',
      zhHans: '安静厉害',
      ja: '静かにすごい',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 71,
      concept: '不催也会长大',
      zhHant: '慢慢會長大',
      zhHans: '慢慢会长大',
      ja: 'そのうち育つ',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 72,
      concept: '允许留到明天',
      zhHant: '明天也可以',
      zhHans: '明天也可以',
      ja: '明日でもいい',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 73,
      concept: '先照顾一下自己',
      zhHant: '自己抱抱',
      zhHans: '自己抱抱',
      ja: '自分よしよし',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 74,
      concept: '专门搜查小确幸',
      zhHant: '小確幸搜查員',
      zhHans: '小确幸搜查员',
      ja: 'ごきげん捜査員',
      category: CompanionNameCategory.gentleTwist,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 75,
      concept: '收集所有雨天',
      zhHant: '雨天收藏家',
      zhHans: '雨天收藏家',
      ja: '雨の日コレクター',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 76,
      concept: '好运还在候补',
      zhHant: '好運候補生',
      zhHans: '好运候补生',
      ja: '幸運候補生',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 77,
      concept: '迷路也算前进',
      zhHant: '迷路也前進',
      zhHans: '迷路也前进',
      ja: '迷って前進',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 78,
      concept: '不张扬地发光',
      zhHant: '低調發光',
      zhHans: '低调发光',
      ja: 'こっそり発光',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 79,
      concept: '平凡本身是超能力',
      zhHant: '平凡超能力',
      zhHans: '平凡超能力',
      ja: 'ふつう超能力',
      category: CompanionNameCategory.gentleTwist,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 80,
      concept: '今天先过关就好',
      zhHant: '今天先過關',
      zhHans: '今天先及格',
      ja: '今日は合格',
      category: CompanionNameCategory.gentleTwist,
      tone: '治愈',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 81,
      concept: '奶茶像一颗电池',
      zhHant: '珍奶電池',
      zhHans: '奶茶电池',
      ja: 'ミルクティー電池',
      category: CompanionNameCategory.foodSupply,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 82,
      concept: '咖啡负责开机',
      zhHant: '咖啡開機',
      zhHans: '咖啡开机',
      ja: 'コーヒー起動',
      category: CompanionNameCategory.foodSupply,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 83,
      concept: '饭团负责回血',
      zhHant: '飯糰回血',
      zhHans: '饭团回血',
      ja: 'おにぎり回復',
      category: CompanionNameCategory.foodSupply,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 84,
      concept: '布丁守护世界',
      zhHant: '布丁護法',
      zhHans: '布丁护法',
      ja: 'プリン守護',
      category: CompanionNameCategory.foodSupply,
      tone: '荒诞',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 85,
      concept: '深夜召唤食物',
      zhHant: '宵夜召喚師',
      zhHans: '夜宵召唤师',
      ja: '夜食召喚士',
      category: CompanionNameCategory.foodSupply,
      tone: '荒诞',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 86,
      concept: '零食负责气场',
      zhHant: '零食怪',
      zhHans: '零食怪',
      ja: 'おやつ番長',
      category: CompanionNameCategory.foodSupply,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 87,
      concept: '饼干是备用能源',
      zhHant: '餅乾備援隊',
      zhHans: '饼干备用队',
      ja: 'クッキー予備隊',
      category: CompanionNameCategory.foodSupply,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 88,
      concept: '午餐是一种信仰',
      zhHant: '午餐信徒',
      zhHans: '午饭信徒',
      ja: 'ランチ信者',
      category: CompanionNameCategory.foodSupply,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 89,
      concept: '定期巡视冰箱',
      zhHant: '冰箱巡邏員',
      zhHans: '冰箱巡逻员',
      ja: '冷蔵庫パトロール',
      category: CompanionNameCategory.foodSupply,
      tone: '趣味',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 90,
      concept: '糖分负责指挥行动',
      zhHant: '糖分指揮官',
      zhHans: '糖分指挥官',
      ja: '糖分司令',
      category: CompanionNameCategory.foodSupply,
      tone: '荒诞',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 91,
      concept: '在宇宙里摸鱼',
      zhHant: '宇宙摸魚員',
      zhHans: '宇宙摸鱼员',
      ja: '宇宙休憩係',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '荒诞',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 92,
      concept: '暂时住在地球',
      zhHant: '地球暫住客',
      zhHans: '地球暂住客',
      ja: '地球の仮住人',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '荒诞',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 93,
      concept: '今天的角色尚未加载',
      zhHant: '角色載入中',
      zhHans: '角色加载中',
      ja: 'キャラロード中',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 94,
      concept: '计划完美但没有行动',
      zhHant: '計畫很完整',
      zhHans: '计划很完整',
      ja: '計画だけ完璧',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 95,
      concept: '明天一定会做到',
      zhHant: '明天一定',
      zhHans: '明天一定',
      ja: '明日こそ',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 96,
      concept: '反派今天休假',
      zhHant: '反派休假中',
      zhHans: '反派休假中',
      ja: '悪役休暇中',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 97,
      concept: '已读但不回的神兽',
      zhHant: '已讀不回獸',
      zhHans: '已读不回兽',
      ja: '既読スルー獣',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 98,
      concept: '认真状态只有三秒',
      zhHant: '三秒認真',
      zhHans: '三秒认真',
      ja: '三秒だけ本気',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小腹黑',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 99,
      concept: '主角也有备用版本',
      zhHant: '備用主角',
      zhHans: '备用主角',
      ja: '予備の主役',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小反转',
      isInitialDefault: true,
    ),
    CompanionNameEntry(
      id: 100,
      concept: '世界可以稍后处理',
      zhHant: '世界待會兒',
      zhHans: '世界等会儿',
      ja: '世界はあとで',
      category: CompanionNameCategory.absurdEasterEgg,
      tone: '小反转',
      isInitialDefault: true,
    ),
  ];

  static List<CompanionNameEntry> get defaultInitialPool =>
      all.where((e) => e.isInitialDefault).toList(growable: false);

  static CompanionNameEntry initialDefaultEntry({Random? random}) {
    final rng = random ?? Random();
    final pool = defaultInitialPool;
    return pool[rng.nextInt(pool.length)];
  }

  static String initialDefaultName(String languageCode, {Random? random}) {
    return initialDefaultEntry(random: random).nameForLanguage(languageCode);
  }

  static CompanionNameEntry randomEntry({
    String? currentName,
    String? languageCode,
    Random? random,
  }) {
    final rng = random ?? Random();
    final currentClean = currentName?.trim();
    final candidates = all.where((e) {
      if (currentClean == null || currentClean.isEmpty) return true;
      if (languageCode != null) {
        return e.nameForLanguage(languageCode) != currentClean;
      }
      return e.zhHant != currentClean &&
          e.zhHans != currentClean &&
          e.ja != currentClean;
    }).toList(growable: false);

    final pool = candidates.isNotEmpty ? candidates : all;
    return pool[rng.nextInt(pool.length)];
  }

  static String randomName(
    String languageCode, {
    String? currentName,
    Random? random,
  }) {
    return randomEntry(
      currentName: currentName,
      languageCode: languageCode,
      random: random,
    ).nameForLanguage(languageCode);
  }
}
